[package]
name = "nix-user-chroot"
description = "Install & Run nix without root permissions"
license = "MIT"
version = "1.1.1"
authors = ["JÃ¶rg Thalheim <joerg@thalheim.io>"]
edition = "2018"

[dependencies]
nix = "0.19.*"
libc = "*"
